window.English = [
// --- 動物・生き物 (Animals) ---
  { front: '🐺', back: 'wolf' },
  { front: '🦊', back: 'fox' },
  { front: '🐱', back: 'cat' },
  { front: '🐯', back: 'tiger' },
  { front: '🦁', back: 'lion' },
  { front: '🦇', back: 'bat' },
  { front: '🐵', back: 'monkey' },
  { front: '🦉', back: 'owl' },
  { front: '🐢', back: 'turtle' },
  { front: '🐻‍❄️', back: 'polar bear' },
  { front: '🐨', back: 'koala' },
  { front: '🐴', back: 'horse' },
  { front: '🐹', back: 'hamster' },
  { front: '🦓', back: 'zebra' },
  { front: '🐑', back: 'sheep' },
  { front: '🐖', back: 'pig' },
  { front: '🐄', back: 'cow' },
  { front: '🦒', back: 'giraffe' },
  { front: '🐘', back: 'elephant' },
  { front: '🐫', back: 'camel' },
  { front: '🐣', back: 'chick' },
  { front: '🐓', back: 'rooster' },
  { front: '🕊️', back: 'dove' },
  { front: '🦚', back: 'peacock' },
  { front: '🐬', back: 'dolphin' },
  { front: '🦈', back: 'shark' },
  { front: '🦀', back: 'crab' },
  { front: '🪼', back: 'jellyfish' },
  { front: '🐛', back: 'caterpillar' },
  { front: '🦖', back: 'tyrannosaurus' },
  { front: '🦕', back: 'dinosaur' },
  { front: '🦘', back: 'kangaroo' },
  { front: '🦥', back: 'sloth' },
  { front: '🦦', back: 'otter' },
  { front: '🦩', back: 'flamingo' },
  { front: '🐈', back: 'cat' },
  { front: '🐕', back: 'dog' },
  { front: '🐇', back: 'rabbit' },
  { front: '🦡', back: 'badger' },
  { front: '🦨', back: 'skunk' },
  { front: '🦝', back: 'raccoon' },
  { front: '🦭', back: 'seal' },
  { front: '🦶', back: 'sled' },
  { front: '🪶', back: 'feather' },
  { front: '🥚', back: 'egg' },
  { front: '🦴', back: 'bone' },
  { front: '🦧', back: 'orangutan' },
  { front: '🐀', back: 'rat' },
  { front: '🐁', back: 'mouse' },
  { front: '🐂', back: 'ox' },
  { front: '🐋', back: 'whale' },
  { front: '🐌', back: 'snail' },
  { front: '🐃', back: 'water buffalo' },
  { front: '🐆', back: 'leopard' },
  { front: '🐉', back: 'dragon' },
  { front: '🐊', back: 'crocodile' },
  { front: '🐗', back: 'boar' },
  { front: '🐙', back: 'octopus' },
  { front: '🐚', back: 'seashell' },
  { front: '🐟', back: 'fish' },
  { front: '🐐', back: 'goat' },
  { front: '🐍', back: 'snake' },
  { front: '🐩', back: 'poodle' },
  { front: '🐪', back: 'camel' },
  { front: '🐮', back: 'cow' },
  { front: '🐻', back: 'bear' },
  { front: '🐼', back: 'panda' },
  { front: '🐾', back: 'paw print' },
  { front: '🐿️', back: 'squirrel' },
  { front: '🦆', back: 'duck' },
  { front: '🦅', back: 'eagle' },
  { front: '🦄', back: 'unicorn' },
  { front: '🦃', back: 'turkey' },
  { front: '🦂', back: 'scorpion' },
  { front: '🦌', back: 'deer' },
  { front: '🦍', back: 'gorilla' },
  { front: '🦎', back: 'lizard' },
  { front: '🦏', back: 'rhino' },
  { front: '🦐', back: 'shrimp' },
  { front: '🦑', back: 'squid' },
  { front: '🦣', back: 'mammoth' },
  { front: '🦛', back: 'hippo' },
  { front: '🦙', back: 'llama' },
  { front: '🦔', back: 'hedgehog' },
  { front: '🦫', back: 'beaver' },
  { front: '🦬', back: 'bison' },
  { front: '🫎', back: 'moose' },
  { front: '🫏', back: 'donkey' },
  { front: '🙈', back: 'monkey' },
  { front: '🙉', back: 'monkey' },
  { front: '🙊', back: 'monkey' },
  { front: '🐸', back: 'frog' },
  { front: '🦮', back: 'guide dog' },
  { front: '🐕‍🦺', back: 'service dog' },
  { front: '🐏', back: 'ram' },
  { front: '🐦', back: 'bird' },
  { front: '🐦‍⬛', back: 'crow' },
  { front: '🦜', back: 'parrot' },
  { front: '🦤', back: 'dodo' },
  { front: '🦢', back: 'swan' },
  { front: '🪿', back: 'goose' },
  { front: '🐦‍🔥', back: 'phoenix' },
  { front: '🐧', back: 'penguin' },
  { front: '🫍', back: 'orca / killer whale' },
  { front: '🐠', back: 'tropical fish' },
  { front: '🐡', back: 'blowfish' },
  { front: '🦪', back: 'oyster' },
  { front: '🪸', back: 'coral' },
  { front: '🫧', back: 'bubbles' },
  { front: '🕷️', back: 'spider' },
  { front: '🕸️', back: 'spiderweb' },
  { front: '🐜', back: 'ant' },
  { front: '🦗', back: 'cricket' },
  { front: '🪲', back: 'June bug/June beetle' },
  { front: '🦟', back: 'mosquito' },
  { front: '🪳', back: 'roach' },
  { front: '🪰', back: 'fly' },
  { front: '🐝', back: 'bee' },
  { front: '🐞', back: 'ladybug' },
  { front: '🦋', back: 'butterfly' },
  { front: '🪱', back: 'earthworm' },
  { front: '🦠', back: 'microbe' },

  // --- 食べ物・飲み物 (Food & Drink) ---
  { front: '🍎', back: 'apple' },
  { front: '🍓', back: 'strawberry' },
  { front: '🍉', back: 'watermelon' },
  { front: '🍒', back: 'cherries' },
  { front: '🍍', back: 'pineapple' },
  { front: '🍊', back: 'mandarin' },
  { front: '🍑', back: 'peach' },
  { front: '🥕', back: 'carrot' },
  { front: '🥦', back: 'broccoli' },
  { front: '🥑', back: 'avocado' },
  { front: '🫑', back: 'bell pepper' },
  { front: '🍆', back: 'eggplant' },
  { front: '🍇', back: 'grapes' },
  { front: '🥒', back: 'cucumber' },
  { front: '🍄‍🟫', back: 'mushroom' },
  { front: '🧄', back: 'garlic' },
  { front: '🥬', back: 'leafy greens' },
  { front: '🧅', back: 'onion' },
  { front: '🥔', back: 'potato' },
  { front: '🌽', back: 'corn' },
  { front: '🍅', back: 'tomato' },
  { front: '🍋', back: 'lemon' },
  { front: '🍌', back: 'banana' },
  { front: '🍐', back: 'pear' },
  { front: '🥝', back: 'kiwi' },
  { front: '🥭', back: 'mango' },
  { front: '🥥', back: 'coconut' },
  { front: '🥐', back: 'croissant' },
  { front: '🥖', back: 'baguette' },
  { front: '🍞', back: 'bread' },
  { front: '🧀', back: 'cheese' },
  { front: '🥩', back: 'steak' },
  { front: '🍗', back: 'chicken leg' },
  { front: '🍔', back: 'burger' },
  { front: '🍕', back: 'pizza' },
  { front: '🍜', back: 'ramen' },
  { front: '🍣', back: 'sushi' },
  { front: '🍩', back: 'donut' },
  { front: '🍰', back: 'shortcake' },
  { front: '🍫', back: 'chocolate bar' },
  { front: '☕', back: 'coffee' },
  { front: '🍵', back: 'matcha' },
  { front: '🍺', back: 'beer' },
  { front: '🍷', back: 'wine' },
  { front: '🌶️', back: 'chili pepper' },
  { front: '🍋‍🟩', back: 'lime' },
  { front: '🍈', back: 'melon' },
  { front: '🫛', back: 'peas' },
  { front: '🍏', back: 'green apple' },
  { front: '🫒', back: 'olive' },
  { front: '🫐', back: 'blueberries' },
  { front: '🍠', back: 'sweet potato' },
  { front: '🫜', back: 'red raddish' },
  { front: '🫚', back: 'ginger' },
  { front: '🫘', back: 'beans' },
  { front: '🌰', back: 'chestnut' },
  { front: '🥜', back: 'peanuts' },
  { front: '🫓', back: 'flatbread' },
  { front: '🥯', back: 'bagel' },
  { front: '🧇', back: 'waffle' },
  { front: '🥞', back: 'pancakes' },
  { front: '🍳', back: 'fried egg' },
  { front: '🥓', back: 'bacon' },
  { front: '🍖', back: 'ribs' },
  { front: '🌭', back: 'hot dog' },
  { front: '🥪', back: 'sandwich' },
  { front: '🥨', back: 'pretzel' },
  { front: '🍟', back: 'fries' },
  { front: '🫔', back: 'tamale' },
  { front: '🌮', back: 'taco' },
  { front: '🌯', back: 'burrito' },
  { front: '🥙', back: 'pita' },
  { front: '🧆', back: 'falafel' },
  { front: '🥘', back: 'paella' },
  { front: '🍝', back: 'spaghetti' },
  { front: '🥫', back: 'canned food' },
  { front: '🫕', back: 'fondue' },
  { front: '🥣', back: 'cereal' },
  { front: '🥗', back: 'salad' },
  { front: '🍲', back: 'stew' },
  { front: '🍛', back: 'curry' },
  { front: '🦞', back: 'lobster' },
  { front: '🍤', back: 'tempura' },
  { front: '🥡', back: 'takeout box' },
  { front: '🍚', back: 'rice' },
  { front: '🍱', back: 'bento' },
  { front: '🥟', back: 'dumpling' },
  { front: '🍢', back: 'oden' },
  { front: '🍙', back: 'rice ball' },
  { front: '🍘', back: 'rice cracker' },
  { front: '🍥', back: 'fish cake' },
  { front: '🍡', back: 'dango' },
  { front: '🥠', back: 'fortune cookie' },
  { front: '🥮', back: 'mooncake' },
  { front: '🍧', back: 'shaved ice' },
  { front: '🍨', back: 'ice cream' },
  { front: '🍦', back: 'soft serve' },
  { front: '🥧', back: 'pie' },
  { front: '🍮', back: 'custard (pudding)/crème caramel/flan' },
  { front: '🎂', back: 'birthday cake' },
  { front: '🧁', back: 'cupcake' },
  { front: '🍭', back: 'lollipop' },
  { front: '🍬', back: 'candy' },
  { front: '🍪', back: 'cookie' },
  { front: '🍯', back: 'honey' },
  { front: '🧂', back: 'salt' },
  { front: '🧈', back: 'butter' },
  { front: '🍿', back: 'popcorn' },
  { front: '🧊', back: 'ice cube' },
  { front: '🫙', back: 'jar' },
  { front: '🥤', back: 'soft drink' },
  { front: '🧋', back: 'bubble tea/boba tea' },
  { front: '🧃', back: 'juice box' },
  { front: '🥛', back: 'milk' },
  { front: '🍼', back: 'baby bottle' },
  { front: '🫖', back: 'teapot' },
  { front: '🧉', back: 'Yerba mate' },
  { front: '🍻', back: 'beers' },
  { front: '🥂', back: 'cheers' },
  { front: '🍾', back: 'champagne' },
  { front: '🥃', back: 'whiskey glass' },
  { front: '🫗', back: 'pouring' },
  { front: '🍸', back: 'cocktail' },
  { front: '🍹', back: 'tropical drink' },
  { front: '🍶', back: 'sake' },
  { front: '🥢', back: 'chopsticks' },
  { front: '🍴', back: 'cutlery' },
  { front: '🥄', back: 'spoon' },
  { front: '🔪', back: 'knife' },
  { front: '🍽️', back: 'plate and cutlery' },

  // --- 植物・自然・天気 (Nature & Weather) ---
  { front: '💎', back: 'gem' },
  { front: '🌸', back: 'cherry blossom' },
  { front: '🪻', back: 'hyacinth' },
  { front: '🌷', back: 'tulip' },
  { front: '🌹', back: 'rose' },
  { front: '🌻', back: 'sunflower' },
  { front: '🌼', back: 'blossom' },
  { front: '🌵', back: 'cactus' },
  { front: '🌲', back: 'pine tree' },
  { front: '🌳', back: 'tree' },
  { front: '🍀', back: 'four-leaf clover' },
  { front: '🍁', back: 'maple leaf' },
  { front: '☔', back: 'umbrella' },
  { front: '☀️', back: 'sun' },
  { front: '🌙', back: 'crescent moon' },
  { front: '🌏', back: 'globe' },
  { front: '🌕', back: 'full moon' },
  { front: '⚡', back: 'lightning' },
  { front: '🌈', back: 'rainbow' },
  { front: '🔥', back: 'fire' },
  { front: '💧', back: 'droplet' },
  { front: '🌊', back: 'wave' },
  { front: '❄️', back: 'snowflake' },
  { front: '⭐', back: 'star' },
  { front: '💐', back: 'bouquet' },
  { front: '🥀', back: 'wilted flower' },
  { front: '🌺', back: 'hibiscus' },
  { front: '🪷', back: 'lotus' },
  { front: '💮', back: 'flower stamp' },
  { front: '🏵️', back: 'rosette' },
  { front: '🍂', back: 'fallen leaf' },
  { front: '🍄', back: 'mushroom' },
  { front: '🌾', back: 'sheaf of rice' },
  { front: '🌿', back: 'herb' },
  { front: '🌱', back: 'seedling' },
  { front: '🍃', back: 'leaves in wind' },
  { front: '☘️', back: 'shamrock' },
  { front: '🪴', back: 'houseplant' },
  { front: '🌴', back: 'palm tree' },
  { front: '🪾', back: 'dead tree' },
  { front: '🪵', back: 'wood' },
  { front: '🪹', back: 'empty nest' },
  { front: '🪺', back: 'bird nest' },
  { front: '🪨', back: 'rock' },
  { front: '🛘', back: 'rockfall / rockslide' },
  { front: '⛰️', back: 'mountain' },
  { front: '🏔️', back: 'snowy mountain / snow-capped mountain' },
  { front: '⛄', back: 'snowman' },
  { front: '🌡️', back: 'thermometer' },
  { front: '🌋', back: 'volcano' },
  { front: '🏜️', back: 'desert' },
  { front: '🏞️', back: 'national park' },
  { front: '🌅', back: 'sunrise over the sea' },
  { front: '🌄', back: 'sunrise over mountains' },
  { front: '🏝️', back: 'island' },
  { front: '🏖️', back: 'beach' },
  { front: '🌬️', back: 'wind' },
  { front: '🌀', back: 'cyclone' },
  { front: '🌪️️', back: 'tornado' },
  { front: '☁️', back: 'cloud' },
  { front: '🌨️', back: 'snow' },
  { front: '🌧️', back: 'rain' },
  { front: '🌩️', back: 'thunderstorm' },
  { front: '⛈️', back: 'storm' },
  { front: '🌦️', back: 'sun showers' },
  { front: '🌥️', back: 'partly cloudy' },
  { front: '⛅', back: 'partly sunny' },
  { front: '🌤️', back: 'mostly sunny' },
  { front: '🌞', back: 'sun' },
  { front: '🌝', back: 'full moon' },
  { front: '🌚', back: 'new moon' },
  { front: '🌜', back: 'moon' },
  { front: '🌛', back: 'moon' },
  { front: '🌟', back: 'glowing star' },
  { front: '✨', back: 'sparkles' },
  { front: '🕳️', back: 'hole' },
  { front: '🪐', back: 'planet / Saturn' },
  { front: '🌍', back: 'globe showing Europe-Africa' },
  { front: '🌎', back: 'globe showing Americas' },
  { front: '🌫️', back: 'fog' },
  { front: '🌠', back: 'shooting star' },
  { front: '🌌', back: 'galaxy' },
  { front: '☄️', back: 'comet' },
  { front: '🌑', back: 'new moon' },
  { front: '🌒', back: 'waxing crescent' },
  { front: '🌓', back: 'first quarter moon' },
  { front: '🌔', back: 'waxing gibbous' },
  { front: '🌖', back: 'waning gibbous' },
  { front: '🌗', back: 'last quarter moon' },
  { front: '🌘', back: 'waning crescent' },

  // --- 感情・顔 (Emotions & Faces) ---
  { front: '😄', back: 'grin' },
  { front: '🥲', back: 'tear of joy' },
  { front: '🤤', back: 'drooling' },
  { front: '🥹', back: 'holding back tears' },
  { front: '😱', back: 'screaming' },
  { front: '👻', back: 'ghost' },
  { front: '💀', back: 'skull' },
  { front: '😍', back: 'heart eyes' },
  { front: '😎', back: 'sunglasses' },
  { front: '😢', back: 'crying' },
  { front: '😡', back: 'angry' },
  { front: '🥳', back: 'partying' },
  { front: '😴', back: 'sleeping' },
  { front: '🤖', back: 'robot' },
  { front: '👽', back: 'alien' },
  { front: '💩', back: 'poop' },
  { front: '😀', back: 'grinning' },
  { front: '😃', back: 'smiley' },
  { front: '😁', back: 'beaming' },
  { front: '😆', back: 'laughing' },
  { front: '😅', back: 'sweat smile' },
  { front: '😂', back: 'laugh crying' },
  { front: '🤣', back: 'rofl' },
  { front: '😭', back: 'sobbing' },
  { front: '😉', back: 'wink' },
  { front: '😗', back: 'kiss' },
  { front: '😙', back: 'kiss smiling' },
  { front: '😚', back: 'kiss eyes closed' },
  { front: '😘', back: 'blow kiss' },
  { front: '🥰', back: 'loving' },
  { front: '🤩', back: 'star struck' },
  { front: '🫠', back: 'melting' },
  { front: '🙃', back: 'upside down' },
  { front: '🙂', back: 'slight smile' },
  { front: '😊', back: 'blushing' },
  { front: '☺️', back: 'smile' },
  { front: '😌', back: 'relieved' },
  { front: '🙂‍↕️', back: 'nodding' },
  { front: '🙂‍↔️', back: 'shaking head' },
  { front: '😏', back: 'smirk' },
  { front: '😋', back: 'yum' },
  { front: '😛', back: 'tongue out' },
  { front: '😝', back: 'squint tongue' },
  { front: '😜', back: 'wink tongue' },
  { front: '🤪', back: 'zany' },
  { front: '🫪', back: 'distorted' },
  { front: '😔', back: 'pensive' },
  { front: '🥺', back: 'pleading' },
  { front: '😬', back: 'grimacing' },
  { front: '😑', back: 'expressionless' },
  { front: '😐', back: 'neutral' },
  { front: '😶', back: 'speechless' },
  { front: '😶‍🌫️', back: 'in the clouds' },
  { front: '🫥', back: 'invisible' },
  { front: '🤐', back: 'zipped lips' },
  { front: '🫡', back: 'salute' },
  { front: '🤔', back: 'thinking' },
  { front: '🤫', back: 'shushing' },
  { front: '🫢', back: 'gasps' },
  { front: '🤭', back: 'giggling' },
  { front: '🥱', back: 'yawning' },
  { front: '🤗', back: 'hugging' },
  { front: '🫣', back: 'peeking' },
  { front: '🤨', back: 'skeptical' },
  { front: '🧐', back: 'monocle' },
  { front: '😒', back: 'unamused' },
  { front: '🙄', back: 'eye roll' },
  { front: '😮‍💨', back: 'exhaling' },
  { front: '😤', back: 'triumph' },
  { front: '🤬', back: 'cursing' },
  { front: '😞', back: 'disappointed' },
  { front: '😓', back: 'sweating' },
  { front: '😟', back: 'worried' },
  { front: '😥', back: 'relieved sad' },
  { front: '☹️', back: 'frowning' },
  { front: '🙁', back: 'slight frown' },
  { front: '🫤', back: 'skeptical' },
  { front: '😕', back: 'confused' },
  { front: '😰', back: 'anxious' },
  { front: '😨', back: 'fearful' },
  { front: '😧', back: 'anguished' },
  { front: '😦', back: 'frowning open mouth' },
  { front: '😮', back: 'open mouth' },
  { front: '😯', back: 'hushed' },
  { front: '😲', back: 'astonished' },
  { front: '😳', back: 'flushed' },
  { front: '🤯', back: 'mind blown' },
  { front: '😖', back: 'confounded' },
  { front: '😣', back: 'persevering' },
  { front: '😩', back: 'weary' },
  { front: '😫', back: 'tired' },
  { front: '😵', back: 'dizzy' },
  { front: '😵‍💫', back: 'spiral eyes' },
  { front: '🫨', back: 'shaking' },
  { front: '🥴', back: 'woozy' },
  { front: '🥵', back: 'hot' },
  { front: '🥶', back: 'cold' },
  { front: '🤢', back: 'nauseous' },
  { front: '🤮', back: 'vomiting' },
  { front: '🫩', back: 'holding tears' },
  { front: '😪', back: 'sleepy' },
  { front: '🤧', back: 'sneezing' },
  { front: '🤒', back: 'sick' },
  { front: '🤕', back: 'injured' },
  { front: '😷', back: 'masked' },
  { front: '🤥', back: 'lying' },
  { front: '😇', back: 'angel' },
  { front: '🤠', back: 'cowboy' },
  { front: '🤑', back: 'rich' },
  { front: '🤓', back: 'nerd' },
  { front: '🥸', back: 'disguised' },
  { front: '🤡', back: 'clown' },
  { front: '😈', back: 'devil' },
  { front: '👿', back: 'angry devil' },
  { front: '☠️', back: 'skull and crossbones' },
  { front: '👹', back: 'ogre' },
  { front: '👺', back: 'goblin' },
  { front: '👾', back: 'space invader' },
  { front: '😺', back: 'grinning cat' },
  { front: '😸', back: 'happy cat' },
  { front: '😹', back: 'laughing cat' },
  { front: '😻', back: 'heart cat' },
  { front: '😼', back: 'smirking cat' },
  { front: '😽', back: 'kissing cat' },
  { front: '🙀', back: 'scared cat' },
  { front: '😿', back: 'crying cat' },
  { front: '😾', back: 'pouting cat' },
  { front: '💫', back: 'dizzy' },
  { front: '💥', back: 'boom' },
  { front: '🫯', back: 'fingerprint' },
  { front: '💢', back: 'anger' },
  { front: '💨', back: 'dash' },
  { front: '💤', back: 'zzz' },
  { front: '💯', back: 'hundred' },
  { front: '🎊', back: 'confetti' },
  { front: '❤️', back: 'red heart' },
  { front: '🧡', back: 'orange heart' },
  { front: '💛', back: 'yellow heart' },
  { front: '💚', back: 'green heart' },
  { front: '🩵', back: 'light blue heart' },
  { front: '💙', back: 'blue heart' },
  { front: '💜', back: 'purple heart' },
  { front: '🤎', back: 'brown heart' },
  { front: '🖤', back: 'black heart' },
  { front: '🩶', back: 'grey heart' },
  { front: '🤍', back: 'white heart' },
  { front: '🩷', back: 'pink heart' },
  { front: '💘', back: 'heart with arrow' },
  { front: '💝', back: 'gift heart' },
  { front: '💖', back: 'sparkling heart' },
  { front: '💗', back: 'growing heart' },
  { front: '💓', back: 'beating heart' },
  { front: '💞', back: 'revolving hearts' },
  { front: '💕', back: 'two hearts' },
  { front: '💌', back: 'love letter' },
  { front: '💟', back: 'heart decoration' },
  { front: '♥️', back: 'heart suit' },
  { front: '❣️', back: 'heart exclamation' },
  { front: '❤️‍🩹', back: 'mending heart' },
  { front: '💔', back: 'broken heart' },
  { front: '❤️‍🔥', back: 'heart on fire' },
  { front: '💋', back: 'kiss mark' },
  { front: '🫂', back: 'hug' },
  { front: '👥', back: 'silhouettes' },
  { front: '👤', back: 'silhouette' },
  { front: '🗣️', back: 'speaking head' },
  { front: '👣', back: 'footprints' },
  { front: '🫆', back: 'fingerprint' },
  { front: '💦', back: 'sweat drops' },
  { front: '🧠', back: 'brain' },
  { front: '🫀', back: 'heart' },
  { front: '🫁', back: 'lungs' },
  { front: '🩸', back: 'blood' },
  { front: '🦷', back: 'tooth' },
  { front: '👀', back: 'eyes' },
  { front: '👁️', back: 'eye' },
  { front: '👄', back: 'mouth' },
  { front: '🫦', back: 'biting lip' },
  { front: '👅', back: 'tongue' },
  { front: '👃🏻', back: 'nose' },
  { front: '👂🏻', back: 'ear' },
  { front: '🦻🏻', back: 'ear with hearing aid' },
  { front: '🦶🏻', back: 'foot' },
  { front: '🦵🏻', back: 'leg' },
  { front: '🦿', back: 'prosthetic leg' },
  { front: '🦾', back: 'prosthetic arm' },
  { front: '💪🏻', back: 'biceps' },
  { front: '👏🏻', back: 'clapping' },
  { front: '👍🏻', back: 'thumbs up' },
  { front: '🫶🏻', back: 'heart hands' },
  { front: '🙌🏻', back: 'raising hands' },
  { front: '👐🏻', back: 'open hands' },
  { front: '🤲🏻', back: 'cupped hands' },
  { front: '🤜🏻', back: 'right fist' },
  { front: '🤛🏻', back: 'left fist' },
  { front: '✊🏻', back: 'raised fist' },
  { front: '👊🏻', back: 'fist bump' },
  { front: '🫳🏻', back: 'palm down' },
  { front: '🫴🏻', back: 'palm up' },
  { front: '🫱🏻', back: 'right hand' },
  { front: '🫲🏻', back: 'left hand' },
  { front: '🫸🏻', back: 'pushing hand' },
  { front: '🫷🏻', back: 'pushing hand' },
  { front: '👋🏻', back: 'wave' },
  { front: '🤚🏻', back: 'back of hand' },
  { front: '🖐🏻', back: 'spread hand' },
  { front: '✋🏻', back: 'raised hand' },
  { front: '🖖🏻', back: 'vulcan salute' },
  { front: '🤟🏻', back: 'love you' },
  { front: '🤘🏻', back: 'rock on' },
  { front: '✌🏻', back: 'peace' },
  { front: '🤞🏻', back: 'fingers crossed' },
  { front: '🫰🏻', back: 'finger heart' },
  { front: '🤙🏻', back: 'call me' },
  { front: '🤌🏻', back: 'italian hand' },
  { front: '🤏🏻', back: 'pinched' },
  { front: '👌🏻', back: 'ok' },
  { front: '🫵🏻', back: 'pointing at you' },
  { front: '👉🏻', back: 'pointing right' },
  { front: '👈🏻', back: 'pointing left' },
  { front: '☝🏻', back: 'pointing up' },
  { front: '👆🏻', back: 'pointing up' },
  { front: '👇🏻', back: 'pointing down' },
  { front: '✍🏻', back: 'writing' },
  { front: '🤳🏻', back: 'selfie' },
  { front: '🙏🏻', back: 'prayer' },
  { front: '💅🏻', back: 'nails' },
  { front: '🤝🏻', back: 'handshake' },



  // --- 職業・人物 (Professions & People) ---
  { front: '👩🏻‍🎨', back: 'artist' },
  { front: '👩🏻‍🍳', back: 'chef' },
  { front: '👩🏻‍🚒', back: 'firefighter' },
  { front: '👩🏻‍🌾', back: 'farmer' },
  { front: '👩🏻‍✈️', back: 'pilot' },
  { front: '👩🏻‍🎓', back: 'student' },
  { front: '👩🏻‍🎤', back: 'singer' },
  { front: '👩🏻‍⚖️', back: 'judge' },
  { front: '🙇🏻‍♀️', back: 'bowing' },
  { front: '🙋🏻‍♀️', back: 'raising hand' },
  { front: '💁🏻‍♀️', back: 'information desk' },
  { front: '🙆🏻‍♀️', back: 'ok gesture' },
  { front: '🙅🏻‍♀️', back: 'no gesture' },
  { front: '🤷🏻‍♀️', back: 'shrugging' },
  { front: '🤦🏻‍♀️', back: 'facepalm' },
  { front: '🙍🏻‍♀️', back: 'frowning' },
  { front: '🙎🏻‍♀️', back: 'pouting' },
  { front: '🧏🏻‍♀️', back: 'deaf' },
  { front: '💆🏻‍♀️', back: 'massage' },
  { front: '💇🏻‍♀️', back: 'haircut' },
  { front: '🧖🏻‍♀️', back: 'sauna' },
  { front: '🛀🏻', back: 'bath' },
  { front: '🛌🏻', back: 'sleeping in bed' },
  { front: '🧘🏻‍♀️', back: 'meditating' },
  { front: '🧍🏻‍♀️', back: 'standing' },
  { front: '🤸🏻‍♀️', back: 'cartwheel' },
  { front: '🧎🏻‍♀️', back: 'kneeling' },
  { front: '👩🏻‍🦼', back: 'wheelchair' },
  { front: '👩🏻‍🦽', back: 'wheelchair' },
  { front: '👩🏻‍🦯', back: 'cane' },
  { front: '🚶🏻‍♀️', back: 'walking' },
  { front: '🏃🏻‍♀️', back: 'running' },
  { front: '⛹🏻‍♀️', back: 'dribbling' },
  { front: '🤾🏻‍♀️', back: 'handball' },
  { front: '🚴🏻‍♀️', back: 'biking' },
  { front: '🚵🏻‍♀️', back: 'mountain biking' },
  { front: '🧗🏻‍♀️', back: 'climbing' },
  { front: '🏋🏻‍♀️', back: 'weightlifting' },
  { front: '🤼', back: 'wrestling' },
  { front: '🤼‍♂️', back: 'wrestling' },
  { front: '🤼‍♀️', back: 'wrestling' },
  { front: '🤹🏻‍♀️', back: 'juggling' },
  { front: '🏌🏻‍♀️', back: 'golfing' },
  { front: '🏇🏻', back: 'horse racing' },
  { front: '🤺', back: 'fencing' },
  { front: '🏂🏻', back: 'snowboarding' },
  { front: '🪂', back: 'skydiving' },
  { front: '🏄🏻‍♀️', back: 'surfing' },
  { front: '🚣🏻‍♀️', back: 'rowing' },
  { front: '🏊🏻‍♀️', back: 'swimming' },
  { front: '🤽🏻‍♀️', back: 'water polo' },
  { front: '🧜🏻‍♀️', back: 'mermaid' },
  { front: '🧚🏻‍♀️', back: 'fairy' },
  { front: '🧞‍♀️', back: 'genie' },
  { front: '🧝🏻‍♀️', back: 'elf' },
  { front: '🧙🏻‍♀️', back: 'witch' },
  { front: '🧛🏻‍♀️', back: 'vampire' },
  { front: '🧟‍♀️', back: 'zombie' },
  { front: '🧌', back: 'troll' },
  { front: '🫈', back: 'person with crown' },
  { front: '🦸🏻‍♀️', back: 'superhero' },
  { front: '🦹🏻‍♀️', back: 'supervillain' },
  { front: '🤶🏻', back: 'mrs claus' },
  { front: '🥷🏻', back: 'ninja' },
  { front: '💂🏻‍♀️', back: 'guard' },
  { front: '👸🏻', back: 'princess' },
  { front: '🤵🏻‍♀️', back: 'tuxedo' },
  { front: '👰🏻‍♀️️', back: 'bride' },
  { front: '👩🏻‍🚀', back: 'astronaut' },
  { front: '👷🏻‍♀️', back: 'construction worker' },
  { front: '👮🏻‍♀️', back: 'police officer' },
  { front: '🕵🏻‍♀️', back: 'detective' },
  { front: '👩🏻‍🔬', back: 'scientist' },
  { front: '👩🏻‍⚕️', back: 'medic' },
  { front: '👩🏻‍🔧', back: 'mechanic' },
  { front: '👩🏻‍🏭', back: 'factory worker' },
  { front: '👩🏻‍🏫', back: 'teacher' },
  { front: '👩🏻‍💼', back: 'office worker' },
  { front: '👩🏻‍💻', back: 'coder' },
  { front: '👳🏻‍♀️', back: 'turban' },
  { front: '🧕🏻', back: 'headscarf' },
  { front: '👲🏻', back: 'skullcap' },
  { front: '👼🏻', back: 'angel' },
  { front: '👶🏻', back: 'baby' },
  { front: '👧🏻', back: 'girl' },
  { front: '👩🏻', back: 'woman' },
  { front: '👵🏻', back: 'elderly woman' },
  { front: '👩🏻‍‍🦳', back: 'white hair' },
  { front: '👩🏻‍🦰', back: 'red hair' },
  { front: '👱🏻‍♀️', back: 'blonde' },
  { front: '👩🏻‍🦱', back: 'curly hair' },
  { front: '👩🏻‍‍🦲', back: 'bald' },
  { front: '🧔🏻‍♀️', back: 'beard' },
  { front: '🕴🏻', back: 'levitating' },
  { front: '🧑🏻‍🩰', back: 'ballet dancer' },
  { front: '💃🏻', back: 'dancer' },
  { front: '🕺🏻', back: 'dancer' },
  { front: '👯', back: 'bunny ears' },
  { front: '🤰🏻', back: 'pregnant' },
  { front: '🤱🏻', back: 'breastfeeding' },
  { front: '👩🏻‍‍🍼', back: 'feeding baby' }
];